version: '3'

services:
  mongodb:
    image: khezen/mongo:3-slim
    environment:
      AUTH: y
      ADMIN_USER: readings
      ADMIN_PWD: secret
      DB_NAME: readings
      DB_USER: readings
      DB_PWD: secret
    ports:
      - 27017

  readings:
    build: .
    environment:
      DEBUG: 1
      MONGODB_HOST: mongodb
      MONGODB_USER: readings
      MONGODB_PASSWORD: secret
    ports:
      - 80
    depends_on:
      - mongodb

networks: {}

volumes: {}
